language: node_js
node_js:
  - '0.10'
  - '0.12'
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.8"
  - "5.12"
  - "6.11"
  - "7.10"
cache:
    directories:
        - node_modules
dist:
    precise
branches:
  only:
    - feature
script:
    - npm run lint